import type { CSSProperties } from "react";

export const s = {
  wrap: { padding: "20px 24px 32px", display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  kpiRow: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 12,
  } satisfies CSSProperties,
  acceptCard: {
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    borderRadius: 8,
    padding: 16,
    display: "flex",
    flexDirection: "column",
    gap: 4,
    minHeight: 88,
    position: "relative",
  } satisfies CSSProperties,
  acceptLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  } satisfies CSSProperties,
  acceptValueRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 4,
  } satisfies CSSProperties,
  acceptValue: { fontSize: 28, fontWeight: 700 } satisfies CSSProperties,
  acceptSuffix: { fontSize: 18, color: "var(--text-muted)" } satisfies CSSProperties,

  panelsRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
  } satisfies CSSProperties,
  panel: {
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    borderRadius: 8,
    padding: 16,
    minHeight: 200,
  } satisfies CSSProperties,
  panelHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    marginBottom: 12,
  } satisfies CSSProperties,
  agentsList: { display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  agentRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 6,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  agentName: { flex: 1, fontSize: 13, fontWeight: 500 } satisfies CSSProperties,
  agentOpen: {
    fontSize: 12,
    color: "var(--accent)",
    textDecoration: "none",
    fontWeight: 600,
  } satisfies CSSProperties,
  emptyText: { fontSize: 13, color: "var(--text-muted)", padding: "8px 0" } satisfies CSSProperties,
} as const;
