import type { CSSProperties } from "react";

/** Co-located styles for TourView — mirrors ContextView's styles.ts. */
export const s = {
  page: { padding: "24px 32px 44px", maxWidth: 1100, margin: "0 auto" } satisfies CSSProperties,
  header: { display: "flex", alignItems: "flex-start", gap: 14, marginBottom: 10 } satisfies CSSProperties,
  headerText: { flex: 1 } satisfies CSSProperties,
  h1: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  accent: { color: "var(--accent)" } satisfies CSSProperties,
  metaRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    marginTop: 6,
    fontSize: 13,
    color: "var(--text-secondary)",
    flexWrap: "wrap",
  } satisfies CSSProperties,
  metaItem: { display: "flex", alignItems: "center", gap: 6 } satisfies CSSProperties,
  loadingList: { display: "flex", flexDirection: "column", gap: 10, marginTop: 20 } satisfies CSSProperties,
  toc: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: "14px 16px",
    margin: "18px 0",
  } satisfies CSSProperties,
  tocTitle: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 10,
  } satisfies CSSProperties,
  tocList: { display: "flex", flexWrap: "wrap", gap: 8 } satisfies CSSProperties,
  tocLink: {
    fontSize: 13,
    color: "var(--text-secondary)",
    textDecoration: "none",
    padding: "4px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
  } satisfies CSSProperties,
  sections: { display: "flex", flexDirection: "column", gap: 16, marginTop: 8 } satisfies CSSProperties,
  sectionCard: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: 20,
  } satisfies CSSProperties,
  body: { fontSize: 14, lineHeight: 1.6, color: "var(--text-primary)" } satisfies CSSProperties,
  linksList: { display: "flex", flexDirection: "column", gap: 8, marginTop: 14, paddingLeft: 20 } satisfies CSSProperties,
  linkItem: { display: "flex", alignItems: "center", gap: 10, fontSize: 13.5 } satisfies CSSProperties,
  linkLabel: { color: "var(--text-secondary)" } satisfies CSSProperties,
  commandsList: { display: "flex", flexDirection: "column", gap: 8, marginTop: 14 } satisfies CSSProperties,
  commandRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "8px 12px",
    background: "var(--bg-base, transparent)",
  } satisfies CSSProperties,
  footer: {
    marginTop: 24,
    paddingTop: 14,
    borderTop: "1px solid var(--border)",
    fontSize: 12.5,
    color: "var(--text-muted)",
    display: "flex",
    gap: 14,
    flexWrap: "wrap",
  } satisfies CSSProperties,
} as const;
