import type { CSSProperties } from "react";

export const s = {
  card: {
    display: "flex",
    gap: 16,
    padding: 16,
    borderRadius: 9,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  dimmed: { opacity: 0.5 } satisfies CSSProperties,
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  topRow: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  rule: {
    fontStyle: "italic",
    fontSize: 15,
    fontWeight: 500,
    color: "var(--text-primary)",
    cursor: "text",
    lineHeight: 1.4,
  } satisfies CSSProperties,
  ruleInput: {
    flex: 1,
    fontStyle: "italic",
    fontSize: 15,
    fontWeight: 500,
    background: "var(--bg-base)",
    border: "1px solid var(--accent)",
    borderRadius: 6,
    padding: "6px 8px",
    color: "var(--text-primary)",
    outline: "none",
  } satisfies CSSProperties,
  evidence: {
    border: "1px solid var(--border)",
    borderRadius: 7,
    background: "var(--bg-base)",
    overflow: "hidden",
  } satisfies CSSProperties,
  evidenceHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    borderBottom: "1px solid var(--border)",
    fontSize: 12,
  } satisfies CSSProperties,
  evidencePath: { color: "var(--accent)", textDecoration: "none" } satisfies CSSProperties,
  code: {
    margin: 0,
    padding: "10px 12px",
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  } satisfies CSSProperties,
  confidenceRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  confidenceBar: { flex: 1 } satisfies CSSProperties,
  confidenceLabel: { fontSize: 12, fontWeight: 600, minWidth: 60, color: "var(--text-secondary)" } satisfies CSSProperties,
  actions: { display: "flex", flexDirection: "column", gap: 8, alignSelf: "flex-start" } satisfies CSSProperties,
} as const;
